DELETE FROM group_replies;
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('مرحبا', 'مرحباً بك 🤍');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('اهلا', 'أهلاً وسهلاً 🌹');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('كيفك', 'بخير الحمدلله، كيفك أنت؟');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('تمام', 'الحمد لله على السلامة');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('الحمدلله', 'الحمد لله دائماً وأبداً');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('الله', 'الله أكبر 🤲');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('الحب', '❤️');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('قلب', '💙');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('ورد', '🌹');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('زهرة', '🌸');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('قمر', '🌙');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('نجم', '⭐');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('شمس', '☀️');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('مطر', '🌧️');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('ثلج', '❄️');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('عسل', '🍯');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('قهوة', '☕');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('شاي', '🍵');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('بيتزا', '🍕');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('برجر', '🍔');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('فطور', '🍳');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('غدا', '🍲');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('عشاء', '🍽️');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('جوعان', 'تغدى معانا 🍔');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('عطشان', 'اشرب مويه 💧');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('نعسان', 'تصبح على خير 🌙');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('تعبان', 'الله يعافيك 💪');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('مريض', 'الشفاء العاجل 🤲');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('فرحان', 'فرحتك تفرحنا 🎉');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('زعلان', 'لا تزعل، احنا معاك 🤍');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('وحيد', 'انت مش وحيد، احنا هنا 👥');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('ملل', 'تعال نونس 😄');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('ضحك', '😂');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('بكاء', '😢');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('غضب', '😠');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('حب', '💕');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('سلام', 'سلامات 🌸');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('باي', 'باي 👋');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('تصبح', 'تصبح على خير 🌙');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('صباح', 'صباح الورد 🌹');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('مساء', 'مساء النور 💫');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('ليلة', 'ليلة سعيدة 🌙');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('نهار', 'نهاركم سعيد ☀️');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('جمعة', 'جمعة مباركة 🤲');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('عيد', 'كل عام وانت بخير 🎉');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('رمضان', 'رمضان كريم 🌙');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('فطر', 'كل عام وأنتم بخير');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('اضحى', 'تقبل الله طاعتكم');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('سنة', 'وأنت بخير 🎉');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('مبروك', 'مبروووك 🎉🎉');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('ترقية', 'مبروك الترقية 🎉');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('زواج', 'الف مبروك الزواج 💑');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('طفل', 'الف مبروك المولود 👶');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('نجاح', 'مبروك النجاح 📚');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('تخرج', 'مبروك التخرج 🎓');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('وظيفة', 'مبروك الوظيفة الجديدة 💼');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('بيت', 'مبارك البيت الجديد 🏠');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('سيارة', 'مبروك السيارة الجديدة 🚗');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('جوال', 'مبروك الجوال الجديد 📱');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('كمبيوتر', 'مبروك الكمبيوتر 💻');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('شكرا جزيلا', 'العفو، تحت أمرك دائماً 🙏');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('الف شكر', 'الشكر لله 🙏');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('تسلم', 'الله يسلمك 🤍');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('تسلم يدك', 'يدك العافية 🫡');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('يعطيك العافية', 'الله يعافيك ❤️');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('ربي يخليك', 'الله يخليك يارب 🤲');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('ربي يحفظك', 'حفظك الله من كل شر');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('ما قصرت', 'الله لا يقصرك');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('جهد مشكور', 'الله يجزاك خير');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('اقتراح', 'أرسل اقتراحك ع الخاص 📝');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('شكوى', 'تواصل مع المشرفين 📢');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('مشكلة', 'نحاول نحلها 🤝');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('خطأ', 'نعتذر عن الخطأ 🙏');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('تطوير', 'نتطور لنخدكم أفضل 🚀');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('ميزة', 'اقترح ميزتك الجديدة 💡');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('فكرة', 'فكرتك حلوة 👍');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('قروب', 'قروبنا حلوها 👥');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('قناة', 'اشترك في قناتنا 📢');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('بوتات', 'هذا بوتنا المميز 🤖');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('منشن', '@ جميع الاعضاء');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('الكل', 'تم منشن الكل 🔔');
INSERT OR REPLACE INTO group_replies (keyword, reply) VALUES ('واعد', 'واعد واترك 🙂');
SELECT '✅ تم إضافة الردود بنجاح!' as 'النتيجة';
