from telegram import Update
from telegram.ext import ContextTypes

def _t(update, text):
    q = update.callback_query
    q.answer()
    q.edit_message_text(text)

async def admin_activate_all_channels_callback(u,c): _t(u,"⚙️ تفعيل جميع القنوات (قيد التطوير)")
async def admin_add_admin_callback(u,c): _t(u,"➕ إضافة مشرف")
async def admin_add_banned_word_callback(u,c): _t(u,"🚫 إضافة كلمة محظورة")
async def admin_add_reply_callback(u,c): _t(u,"💬 إضافة رد")
async def admin_all_channels_callback(u,c): _t(u,"📢 جميع القنوات")
async def admin_auto_reply_callback(u,c): _t(u,"🔄 الرد التلقائي")
async def admin_auto_reply_select_callback(u,c): _t(u,"🔽 اختيار الرد التلقائي")
async def admin_backup_callback(u,c): _t(u,"💾 النسخ الاحتياطي")
async def admin_backup_settings_callback(u,c): _t(u,"⚙️ إعدادات النسخ الاحتياطي")
async def admin_banned_users_callback(u,c): _t(u,"🚫 المستخدمون المحظورون")
async def admin_banned_words_callback(u,c): _t(u,"📝 الكلمات المحظورة")
async def admin_broadcast_callback(u,c): _t(u,"📣 إذاعة")
async def admin_change_interval_callback(u,c): _t(u,"⏱️ تغيير المدة")
async def admin_confirm_broadcast_callback(u,c): _t(u,"✅ تأكيد الإذاعة")
async def admin_confirm_delete_tickets_callback(u,c): _t(u,"🗑️ تأكيد حذف التذاكر")
async def admin_create_contest_callback(u,c): _t(u,"🏆 إنشاء مسابقة")
async def admin_del_contest_callback(u,c): _t(u,"🗑️ حذف مسابقة")
async def admin_del_reply_callback(u,c): _t(u,"❌ حذف رد")
async def admin_delete_all_tickets_callback(u,c): _t(u,"🧹 حذف جميع التذاكر")
async def admin_force_subscribe_callback(u,c): _t(u,"🔔 الاشتراك الإجباري")
async def admin_list_banned_words_callback(u,c): _t(u,"📋 قائمة الكلمات المحظورة")
async def admin_list_replies_callback(u,c): _t(u,"💬 قائمة الردود")
async def admin_manage_sendcode_callback(u,c): _t(u,"📨 إدارة إرسال الكود")
async def admin_panel_callback(u,c): _t(u,"⚙️ لوحة التحكم")
async def admin_ram_callback(u,c): _t(u,"📊 استخدام الذاكرة")
async def admin_remove_admin_callback(u,c): _t(u,"➖ إزالة مشرف")
async def admin_remove_banned_word_callback(u,c): _t(u,"❌ إزالة كلمة محظورة")
async def admin_replies_callback(u,c): _t(u,"💬 إدارة الردود")
async def admin_send_update_callback(u,c): _t(u,"📬 إرسال تحديث")
async def admin_set_update_channel_callback(u,c): _t(u,"📢 تعيين قناة التحديثات")
async def admin_show_log_channel_callback(u,c): _t(u,"📋 عرض قناة السجلات")
async def admin_show_update_channel_callback(u,c): _t(u,"👁️ عرض قناة التحديثات")
async def admin_stats_callback(u,c): _t(u,"📈 إحصائيات")
async def admin_support_tickets_callback(u,c): _t(u,"🎫 تذاكر الدعم")
async def admin_toggle_auto_backup_callback(u,c): _t(u,"🔄 تفعيل النسخ التلقائي")
async def admin_toggle_channel_ban_callback(u,c): _t(u,"🚫 حظر القنوات")
async def admin_toggle_group_ban_callback(u,c): _t(u,"🚫 حظر المجموعات")
async def admin_unban_all_bot_channels_callback(u,c): _t(u,"🔓 رفع حظر قنوات البوت")
async def admin_unban_all_groups_callback(u,c): _t(u,"🔓 رفع حظر المجموعات")
async def admin_unban_all_users_callback(u,c): _t(u,"🔓 رفع حظر المستخدمين")
async def admin_users_callback(u,c): _t(u,"👥 إدارة المستخدمين")
async def penalty_ban_callback(u,c): _t(u,"🔨 حظر")
async def penalty_kick_callback(u,c): _t(u,"👢 طرد")
async def penalty_menu_callback(u,c): _t(u,"⚖️ قائمة العقوبات")
async def penalty_mute_callback(u,c): _t(u,"🔇 كتم")
async def penalty_mute_duration_callback(u,c): _t(u,"⏳ مدة الكتم")
