services:
  - type: web
    name: relax-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: MAIN_ADMIN_ID
        sync: false
      - key: BOT_NAME
        value: ريلاكس مانيجر
      - key: BOT_USERNAME
        value: Reelaaaxbot
      - key: MAX_FILE_SIZE
        value: 20971520
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.11.0
